import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001f26",
        "on-tertiary": "#003824",
        "tertiary-container": "#1bbd85",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004e5c",
        "on-primary": "#003640",
        "secondary-fixed": "#e1e0ff",
        "on-background": "#dae2fd",
        "on-error-container": "#ffdad6",
        "primary": "#4cd7f6",
        "tertiary-fixed-dim": "#4edea3",
        "outline": "#869397",
        "tertiary": "#4edea3",
        "secondary-fixed-dim": "#c0c1ff",
        "on-error": "#690005",
        "inverse-surface": "#dae2fd",
        "surface-dim": "#0b1326",
        "surface-container": "#171f33",
        "error": "#ffb4ab",
        "surface-container-high": "#222a3d",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-container": "#b0b2ff",
        "primary-fixed-dim": "#4cd7f6",
        "on-secondary": "#1000a9",
        "on-secondary-fixed": "#07006c",
        "primary-container": "#06b6d4",
        "inverse-primary": "#00687a",
        "background": "#0b1326",
        "secondary-container": "#3131c0",
        "on-surface": "#dae2fd",
        "secondary": "#c0c1ff",
        "on-primary-container": "#00424f",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-bright": "#31394d",
        "surface-container-low": "#131b2e",
        "on-surface-variant": "#bcc9cd",
        "primary-fixed": "#acedff",
        "surface-tint": "#4cd7f6",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-lowest": "#060e20",
        "inverse-on-surface": "#283044",
        "outline-variant": "#3d494c",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#00452e",
        "on-tertiary-fixed": "#002113",
        "surface": "#0b1326"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-base": "1rem",
        "space-xs": "0.25rem",
        "gutter-kanban": "1rem",
        "space-md": "0.75rem",
        "space-xl": "1.5rem",
        "sidebar-width": "16rem",
        "margin-page": "1.5rem",
        "space-3xl": "3rem",
        "space-lg": "1.25rem",
        "space-xxs": "0.125rem",
        "space-sm": "0.5rem",
        "drawer-width": "28rem",
        "space-2xl": "2rem"
      },
      fontFamily: {
        "headline-xl-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "numeric-data": ["var(--font-inter)", "Inter", "sans-serif"],
        "kpi-metric": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "title-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        "headline-xl-mobile": ["1.625rem", { lineHeight: "2.125rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "numeric-data": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "kpi-metric": ["1.875rem", { lineHeight: "2.25rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-sm": ["0.75rem", { lineHeight: "1.125rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "400" }],
        "title-md": ["1rem", { lineHeight: "1.375rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}

export default config
